// flow-typed signature: 834663800454e4e33abc7eda4ae4e6eb
// flow-typed version: <<STUB>>/usertiming_v0.1.8/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'usertiming'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'usertiming' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'usertiming/src/usertiming' {
  declare module.exports: any;
}

declare module 'usertiming/test-w3c/idlharness' {
  declare module.exports: any;
}

declare module 'usertiming/test-w3c/testharness' {
  declare module.exports: any;
}

declare module 'usertiming/test-w3c/testharnessreport' {
  declare module.exports: any;
}

declare module 'usertiming/test-w3c/WebIDLParser' {
  declare module.exports: any;
}

declare module 'usertiming/test-w3c/webperftestharness' {
  declare module.exports: any;
}

// Filename aliases
declare module 'usertiming/src/usertiming.js' {
  declare module.exports: $Exports<'usertiming/src/usertiming'>;
}
declare module 'usertiming/test-w3c/idlharness.js' {
  declare module.exports: $Exports<'usertiming/test-w3c/idlharness'>;
}
declare module 'usertiming/test-w3c/testharness.js' {
  declare module.exports: $Exports<'usertiming/test-w3c/testharness'>;
}
declare module 'usertiming/test-w3c/testharnessreport.js' {
  declare module.exports: $Exports<'usertiming/test-w3c/testharnessreport'>;
}
declare module 'usertiming/test-w3c/WebIDLParser.js' {
  declare module.exports: $Exports<'usertiming/test-w3c/WebIDLParser'>;
}
declare module 'usertiming/test-w3c/webperftestharness.js' {
  declare module.exports: $Exports<'usertiming/test-w3c/webperftestharness'>;
}
